= Inform: A C library for information analysis of complex systems
Douglas G. Moore <doug@dglmoore.com>
v0.0.5, June 2017
:toc2:
:toclevels: 2
:source-highlighter: prettify
:stem: latexmath

Inform is a cross-platform C library designed for performing information 
analysis of complex system.

1. The `inform_dist` struct provides discrete, emperical probability
   distributions. These form the basis for all of the information-theoretic
   measures.
2. A collection of information measures built upon the distribution struct
   provide the core algorithms for the library, and are provided through the
   `shannon.h` header.
3. A host of measures of the information dynamics on time series are built upon
   the core information measures. Each measure is housed in its own header, e.g.
   `active_info.h`.

In addition to the core components, a small collection of utilities are also
provided.

:leveloffset: 1

include::getting-started.adoc[]

include::distributions.adoc[]

include::shannon.adoc[]
