= Utilities

== State Binning
All of the currently implemented time series measures are only defined on
discretely-valued time series. However, in practice continuously-valued time
series are ubiquitous. There are two approaches to accomodating continuous
values.

The simplest is to _bin_ the time series, forcing the values into discrete
states. This method has its downsides, namely that the binning is often a bit
unphysical and it can introduce bias. What’s more, without some kind of guiding
principle it can be difficult to decide exactly which binning approach.

The second approach attempts to infer condinuous probability distributions from
continuous data. This is potentially more robust, but more technically
difficult. Unfortunately, *Inform* does not yet have an implementation of
information measures on continuous distributions,
https://github.com/elife-asu/inform/issues/21[but it is in the works].

The `inform/utilities.h` header provides basic binning facilities via the
`inform_bin`, `inform_bin_step` and `inform_bin_bounds` functions.

== State Coalescing

== State Encoding
State encoding is a necessity when complex time series are being analyzed. For
example, latexmath[k]-history must be encoded as an integer in order to
"observe" it using a Dist. What if you are interested in correlating the
aggragate state of one group of nodes with that of another? You’d need to encode
the groups' states as integers. The `inform/utilities.h` header provides this
functionality via the `inform_encode` and `inform_decode` functions.

[IMPORTANT]
================================================================================
As a practical matter, these utility functions should only be used as
a stop-gap while a solution for your problem is implemented in the core library.
"Why?" you ask? Well, these functions are about as efficient as they can be for
one-off state encodings, but most of the time you are interested in encoding
sequences of states. This can be done much more efficiently if you encode the
entire sequence at once. You need domain-specific information to make that
happen.

This being said, these functions aren’t bad just be aware that they may turn
into a bottleneck in whatever you are implementing.
================================================================================
